// Auto-generated by sector_rotation.py — do not edit
const SR_DATA = {
  "generated": "2026-04-21T23:07:03.653480",
  "lookbacks": [
    "1D",
    "1M",
    "3M",
    "6M",
    "1Y"
  ],
  "benchmark": {
    "etf": "SPY",
    "perf_1d": -0.65,
    "perf_1m": 8.56,
    "perf_3m": 4.19,
    "perf_6m": 6.58,
    "perf_1y": null
  },
  "sectors": [
    {
      "rank": 1,
      "etf": "XOP",
      "sector": "Oil & Gas E&P",
      "rs_new_high": false,
      "perf_1d": 2.41,
      "perf_1m": -6.47,
      "perf_3m": 27.67,
      "perf_6m": 35.04,
      "perf_1y": null
    },
    {
      "rank": 2,
      "etf": "SOXX",
      "sector": "Semis Broad",
      "rs_new_high": true,
      "perf_1d": 0.75,
      "perf_1m": 26.52,
      "perf_3m": 24.78,
      "perf_6m": 46.29,
      "perf_1y": null
    },
    {
      "rank": 3,
      "etf": "XSD",
      "sector": "Semis EW",
      "rs_new_high": true,
      "perf_1d": 1.68,
      "perf_1m": 33.59,
      "perf_3m": 22.84,
      "perf_6m": 25.67,
      "perf_1y": null
    },
    {
      "rank": 4,
      "etf": "SMH",
      "sector": "Semis",
      "rs_new_high": true,
      "perf_1d": 0.15,
      "perf_1m": 20.77,
      "perf_3m": 19.02,
      "perf_6m": 35.96,
      "perf_1y": null
    },
    {
      "rank": 5,
      "etf": "XLE",
      "sector": "Energy",
      "rs_new_high": false,
      "perf_1d": 1.45,
      "perf_1m": -5.18,
      "perf_3m": 18.14,
      "perf_6m": 31.92,
      "perf_1y": null
    },
    {
      "rank": 6,
      "etf": "XLK",
      "sector": "Technology",
      "rs_new_high": true,
      "perf_1d": 0.08,
      "perf_1m": 14.48,
      "perf_3m": 9.2,
      "perf_6m": 8.85,
      "perf_1y": null
    },
    {
      "rank": 7,
      "etf": "XBI",
      "sector": "Biotech",
      "rs_new_high": false,
      "perf_1d": -1.02,
      "perf_1m": 13.37,
      "perf_3m": 8.86,
      "perf_6m": 26.94,
      "perf_1y": null
    },
    {
      "rank": 8,
      "etf": "XLB",
      "sector": "Materials",
      "rs_new_high": false,
      "perf_1d": -0.88,
      "perf_1m": 10.69,
      "perf_3m": 7.91,
      "perf_6m": 18.95,
      "perf_1y": null
    },
    {
      "rank": 9,
      "etf": "XLRE",
      "sector": "Real Estate",
      "rs_new_high": false,
      "perf_1d": -1.93,
      "perf_1m": 8.58,
      "perf_3m": 6.46,
      "perf_6m": 5.98,
      "perf_1y": null
    },
    {
      "rank": 10,
      "etf": "TAN",
      "sector": "Solar",
      "rs_new_high": false,
      "perf_1d": -1.57,
      "perf_1m": -0.85,
      "perf_3m": 6.2,
      "perf_6m": 17.44,
      "perf_1y": null
    },
    {
      "rank": 11,
      "etf": "AIQ",
      "sector": "AI Theme",
      "rs_new_high": true,
      "perf_1d": -0.41,
      "perf_1m": 13.34,
      "perf_3m": 5.4,
      "perf_6m": 6.41,
      "perf_1y": null
    },
    {
      "rank": 12,
      "etf": "XLU",
      "sector": "Utilities",
      "rs_new_high": false,
      "perf_1d": -1.75,
      "perf_1m": 1.38,
      "perf_3m": 5.36,
      "perf_6m": -0.4,
      "perf_1y": null
    },
    {
      "rank": 13,
      "etf": "XLI",
      "sector": "Industrials",
      "rs_new_high": false,
      "perf_1d": -1.41,
      "perf_1m": 6.34,
      "perf_3m": 5.13,
      "perf_6m": 13.7,
      "perf_1y": null
    },
    {
      "rank": 14,
      "etf": "IWM",
      "sector": "Small Cap",
      "rs_new_high": true,
      "perf_1d": -1.02,
      "perf_1m": 13.33,
      "perf_3m": 4.73,
      "perf_6m": 13.36,
      "perf_1y": null
    },
    {
      "rank": 15,
      "etf": "XLC",
      "sector": "Comm Svcs",
      "rs_new_high": false,
      "perf_1d": -1.34,
      "perf_1m": 4.73,
      "perf_3m": 3.58,
      "perf_6m": 2.59,
      "perf_1y": null
    },
    {
      "rank": 16,
      "etf": "XLY",
      "sector": "Cons Disc",
      "rs_new_high": false,
      "perf_1d": -0.75,
      "perf_1m": 10.65,
      "perf_3m": 0.07,
      "perf_6m": 1.91,
      "perf_1y": null
    },
    {
      "rank": 17,
      "etf": "XLP",
      "sector": "Cons Staples",
      "rs_new_high": false,
      "perf_1d": -0.67,
      "perf_1m": 1.24,
      "perf_3m": -0.07,
      "perf_6m": 4.05,
      "perf_1y": null
    },
    {
      "rank": 18,
      "etf": "URA",
      "sector": "Uranium/Nuclear",
      "rs_new_high": false,
      "perf_1d": -4.12,
      "perf_1m": 15.72,
      "perf_3m": -0.7,
      "perf_6m": 5.62,
      "perf_1y": null
    },
    {
      "rank": 19,
      "etf": "XLF",
      "sector": "Financials",
      "rs_new_high": false,
      "perf_1d": -0.63,
      "perf_1m": 7.11,
      "perf_3m": -1.19,
      "perf_6m": 1.1,
      "perf_1y": null
    },
    {
      "rank": 20,
      "etf": "ITB",
      "sector": "Homebuilders",
      "rs_new_high": false,
      "perf_1d": 0.15,
      "perf_1m": 13.47,
      "perf_3m": -4.89,
      "perf_6m": -2.88,
      "perf_1y": null
    },
    {
      "rank": 21,
      "etf": "XLV",
      "sector": "Healthcare",
      "rs_new_high": false,
      "perf_1d": -1.02,
      "perf_1m": 0.82,
      "perf_3m": -5.71,
      "perf_6m": 2.7,
      "perf_1y": null
    },
    {
      "rank": 22,
      "etf": "XAR",
      "sector": "Aero & Defense",
      "rs_new_high": false,
      "perf_1d": -3.22,
      "perf_1m": 3.36,
      "perf_3m": -5.8,
      "perf_6m": 13.71,
      "perf_1y": null
    },
    {
      "rank": 23,
      "etf": "BUG",
      "sector": "Cybersecurity",
      "rs_new_high": false,
      "perf_1d": 1.88,
      "perf_1m": 5.17,
      "perf_3m": -7.07,
      "perf_6m": -20.77,
      "perf_1y": null
    },
    {
      "rank": 24,
      "etf": "GDX",
      "sector": "Gold Miners",
      "rs_new_high": false,
      "perf_1d": -6.19,
      "perf_1m": 16.06,
      "perf_3m": -9.53,
      "perf_6m": 18.97,
      "perf_1y": null
    },
    {
      "rank": 25,
      "etf": "IGV",
      "sector": "Software",
      "rs_new_high": false,
      "perf_1d": 0.44,
      "perf_1m": 4.45,
      "perf_3m": -9.64,
      "perf_6m": -23.07,
      "perf_1y": null
    },
    {
      "rank": 26,
      "etf": "WCLD",
      "sector": "Cloud",
      "rs_new_high": false,
      "perf_1d": 0.39,
      "perf_1m": -0.39,
      "perf_3m": -11.22,
      "perf_6m": -18.38,
      "perf_1y": null
    }
  ]
};
